### PR TITLE
Make options non case sensitive for Bash edition 

### PR DESCRIPTION
**Pull request by Jai-JAP**
Make options non case sensitive for Bash edition.
As per https://wiki.bash-hackers.org/syntax/pe#case_modification

### CODE REVIEW

**Comment by Jai-JAP** [comment]
I dont have an Arch linux installation but tested it using [pacapt](https://github.com/icy/pacapt) on TwisterOS.
Works fine.

**Comment by CleanMachine1** [comment]
You should try Arch or on a Pi, Manjaro. 

You'll find to love it over Debian based or Ubuntu

**Review by Itai-Nelken — APPROVED** [review]
Thanks!

**Comment by Jai-JAP** [comment]
> You should try Arch or on a Pi, Manjaro.
> 
> You'll find to love it over Debian based or Ubuntu

sure i will try it when i have spare sd card or a usb stick lying around me

**Pull request merged**
